version: "2"
services:
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    ports:
      - "8083:8083"
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=CBTNUGGETS-DEMO
      - DOCKER_INFLUXDB_INIT_BUCKET=CBTNUGGETS-DEMO-BUCKET
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=veryverysecuretoken
      - INFLUXD_TLS_CERT=/etc/ssl/influxdb-selfsigned.crt
      - INFLUXD_TLS_KEY=/etc/ssl/influxdb-selfsigned.key
    volumes:
      - ./vols/:/var/lib/influxdb2
      - /etc/ssl:/etc/ssl
      # - ./ssl/influxdb-selfsigned.crt:/etc/ssl/influxdb-selfsigned.crt
      # - ./ssl/influxdb-selfsigned.key:/etc/ssl/influxdb-selfsigned.key
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    links:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana
      - /var/lib/grafana/ssl:/var/lib/grafana/ssl
      - /etc/grafana:/etc/grafana
      # - /var/lib/grafana/ssl/grafana.crt:/var/lib/grafana/ssl/grafana.crt
      # - /var/lib/grafana/ssl/grafana.key:/var/lib/grafana/ssl/grafana.key
    environment:
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=/etc/grafana/grafana.crt # /var/lib/grafana/ssl/grafana.crt
      - GF_SERVER_CERT_KEY=/etc/grafana/grafana.key # /var/lib/grafana/ssl/grafana.key
      - GF_INSTALL_PLUGINS=marcusolsson-dynamictext-panel
    restart: always

  telegraf:
    container_name: telegraf
    image: telegraf:latest
    ports:
      - "57000:57000"
    environment:
      - INFLUXDB_TOKEN=veryverysecuretoken
    links:
      - influxdb
    volumes:
      - ./conf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes:
  grafana_data:
